name: Build Release
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install framework7-svelte
      - name: Install
        run: npm i framework7-svelte
